
-- 경제 카테고리
-- 도서ID, 저자명, 출판일 리스트 출력
-- 추란일 기준 오름차순

-- AUTHOR_ID 기준으로 JOIN
SELECT T1.BOOK_ID
     , T2.AUTHOR_NAME
     , SUBSTR(T1.PUBLISHED_DATE,1,10)
FROM BOOK T1
JOIN AUTHOR T2 ON (T1.AUTHOR_ID = T2.AUTHOR_ID)
WHERE T1.CATEGORY = '경제'
ORDER BY T1.PUBLISHED_DATE
